begin;

create table if not exists public.site_leads (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  name text not null
    check (char_length(btrim(name)) between 2 and 80),
  phone text not null
    check (phone ~ '^\+380[0-9]{9}$'),
  phone_raw text null,
  city text not null
    check (char_length(btrim(city)) between 2 and 80),
  role text not null
    check (
      role in (
        'head',
        'manager',
        'board_member',
        'resident',
        'other'
      )
    ),
  message text null
    check (message is null or char_length(message) <= 1000),

  lead_type text not null default 'connect'
    check (
      lead_type in (
        'connect',
        'resident_request',
        'contact',
        'other'
      )
    ),
  status text not null default 'new'
    check (
      status in (
        'new',
        'in_progress',
        'meeting',
        'won',
        'lost'
      )
    ),

  lost_reason text null,
  assigned_to uuid null
    references public.profiles(id)
    on delete set null,
  next_action_at timestamptz null,
  first_response_at timestamptz null,
  closed_at timestamptz null,

  utm_source text null,
  utm_medium text null,
  utm_campaign text null,
  utm_content text null,
  landing_page text null,
  referrer text null,
  user_agent text null,
  first_seen_at timestamptz null,

  lock_version integer not null default 1
    check (lock_version > 0),
  deleted_at timestamptz null
);

create index if not exists site_leads_status_created_idx
  on public.site_leads (status, created_at desc);

create index if not exists site_leads_assigned_status_idx
  on public.site_leads (assigned_to, status);

create index if not exists site_leads_created_idx
  on public.site_leads (created_at desc);

create index if not exists site_leads_city_idx
  on public.site_leads (lower(city));

comment on table public.site_leads is
  'Public company-site leads. Anonymous clients cannot write directly; submissions pass through a validated server boundary.';

alter table public.site_leads enable row level security;

drop policy if exists site_leads_admin_select
  on public.site_leads;
drop policy if exists site_leads_admin_insert
  on public.site_leads;
drop policy if exists site_leads_admin_update
  on public.site_leads;
drop policy if exists site_leads_admin_delete
  on public.site_leads;

create policy site_leads_admin_select
  on public.site_leads
  for select
  to authenticated
  using (public.is_active_admin());

create policy site_leads_admin_insert
  on public.site_leads
  for insert
  to authenticated
  with check (public.is_active_admin());

create policy site_leads_admin_update
  on public.site_leads
  for update
  to authenticated
  using (public.is_active_admin())
  with check (public.is_active_admin());

create policy site_leads_admin_delete
  on public.site_leads
  for delete
  to authenticated
  using (public.is_active_admin());

create table if not exists public.site_rate_limits (
  id bigint generated by default as identity primary key,
  scope text not null,
  subject_hash text not null,
  window_started_at timestamptz not null,
  attempts integer not null default 1
    check (attempts > 0),
  updated_at timestamptz not null default now(),

  unique (scope, subject_hash, window_started_at)
);

create index if not exists site_rate_limits_lookup_idx
  on public.site_rate_limits (
    scope,
    subject_hash,
    window_started_at desc
  );

comment on table public.site_rate_limits is
  'Server-only rate-limit counters. subject_hash contains a one-way hash; raw IP addresses must never be stored.';

alter table public.site_rate_limits enable row level security;

revoke all on table public.site_rate_limits
  from anon, authenticated;

revoke all on sequence public.site_rate_limits_id_seq
  from anon, authenticated;

create or replace function public.consume_site_rate_limit(
  p_scope text,
  p_subject_hash text,
  p_window_seconds integer default 600,
  p_max_attempts integer default 5
)
returns table (
  allowed boolean,
  attempts integer,
  retry_after_seconds integer
)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_now timestamptz := clock_timestamp();
  v_window_seconds integer;
  v_max_attempts integer;
  v_window_started_at timestamptz;
  v_attempts integer;
begin
  v_window_seconds := greatest(1, least(p_window_seconds, 86400));
  v_max_attempts := greatest(1, least(p_max_attempts, 100));

  if nullif(btrim(p_scope), '') is null then
    raise exception 'RATE_LIMIT_SCOPE_REQUIRED';
  end if;

  if nullif(btrim(p_subject_hash), '') is null then
    raise exception 'RATE_LIMIT_SUBJECT_REQUIRED';
  end if;

  v_window_started_at :=
    to_timestamp(
      floor(extract(epoch from v_now) / v_window_seconds)
      * v_window_seconds
    );

  insert into public.site_rate_limits (
    scope,
    subject_hash,
    window_started_at,
    attempts,
    updated_at
  )
  values (
    btrim(p_scope),
    btrim(p_subject_hash),
    v_window_started_at,
    1,
    v_now
  )
  on conflict (scope, subject_hash, window_started_at)
  do update
    set attempts = public.site_rate_limits.attempts + 1,
        updated_at = excluded.updated_at
  returning public.site_rate_limits.attempts
  into v_attempts;

  return query
  select
    v_attempts <= v_max_attempts,
    v_attempts,
    greatest(
      0,
      ceil(
        extract(
          epoch from (
            v_window_started_at
            + make_interval(secs => v_window_seconds)
            - v_now
          )
        )
      )::integer
    );
end;
$$;

revoke all on function public.consume_site_rate_limit(
  text,
  text,
  integer,
  integer
) from public, anon, authenticated;

grant execute on function public.consume_site_rate_limit(
  text,
  text,
  integer,
  integer
) to service_role;

commit;
