begin;

create table if not exists public.site_rate_limits (
  id bigint generated by default as identity primary key,
  scope text not null,
  subject_hash text not null,
  window_started_at timestamptz not null default now(),
  attempt_count integer not null default 0,
  updated_at timestamptz not null default now(),
  constraint site_rate_limits_scope_subject_key unique (scope, subject_hash)
);

create index if not exists site_rate_limits_updated_at_idx
  on public.site_rate_limits (updated_at);

alter table public.site_rate_limits enable row level security;

revoke all on table public.site_rate_limits from anon, authenticated;
grant select, insert, update, delete on table public.site_rate_limits to service_role;

create or replace function public.consume_site_rate_limit(
  p_scope text,
  p_subject_hash text,
  p_window_seconds integer,
  p_max_attempts integer
)
returns table (
  allowed boolean,
  retry_after_seconds integer
)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_now timestamptz := now();
  v_row public.site_rate_limits%rowtype;
  v_window_end timestamptz;
begin
  if coalesce(length(trim(p_scope)), 0) = 0 then
    raise exception 'RATE_LIMIT_SCOPE_REQUIRED';
  end if;

  if coalesce(length(trim(p_subject_hash)), 0) = 0 then
    raise exception 'RATE_LIMIT_SUBJECT_REQUIRED';
  end if;

  if p_window_seconds is null or p_window_seconds <= 0 then
    raise exception 'RATE_LIMIT_WINDOW_INVALID';
  end if;

  if p_max_attempts is null or p_max_attempts <= 0 then
    raise exception 'RATE_LIMIT_MAX_INVALID';
  end if;

  insert into public.site_rate_limits (
    scope,
    subject_hash,
    window_started_at,
    attempt_count,
    updated_at
  )
  values (
    trim(p_scope),
    trim(p_subject_hash),
    v_now,
    1,
    v_now
  )
  on conflict (scope, subject_hash)
  do update set
    window_started_at =
      case
        when public.site_rate_limits.window_started_at
          + make_interval(secs => p_window_seconds) <= v_now
        then v_now
        else public.site_rate_limits.window_started_at
      end,
    attempt_count =
      case
        when public.site_rate_limits.window_started_at
          + make_interval(secs => p_window_seconds) <= v_now
        then 1
        else public.site_rate_limits.attempt_count + 1
      end,
    updated_at = v_now
  returning *
  into v_row;

  v_window_end :=
    v_row.window_started_at + make_interval(secs => p_window_seconds);

  allowed := v_row.attempt_count <= p_max_attempts;
  retry_after_seconds :=
    case
      when allowed then 0
      else greatest(
        1,
        ceil(extract(epoch from (v_window_end - v_now)))::integer
      )
    end;

  return next;
end;
$$;

revoke all on function public.consume_site_rate_limit(text,text,integer,integer)
  from public, anon, authenticated;
grant execute on function public.consume_site_rate_limit(text,text,integer,integer)
  to service_role;

commit;
